// this shorts names are returned by https://www.visualcrossing.com/ WeatherHistory Api
export const WeatherHistoryApiResColumns = {
  temp: {
    id: 'temp',
    name: 'Temperature',
    fieldName: 'temperature',
    type: 2,
    unit: 'degC',
  },
  maxt: {
    id: 'maxt',
    fieldName: 'maxTemperature',
    name: 'Maximum Temperature',
    type: 2,
    unit: 'degC',
  },
  tempmax: {
    id: 'tempmax',
    fieldName: 'maxTemperature',
    name: 'Maximum Temperature',
    type: 2,
    unit: 'degC',
  },
  feelslike: {
    id: 'feelslike',
    fieldName: 'feelslike',
    name: 'Feels like',
    type: 2,
    unit: 'degC',
  },
  tempmin: {
    id: 'tempmin',
    fieldName: 'minTemperature',
    name: 'Minimum Temperature',
    type: 2,
    unit: 'degC',
  },

  visibility: {
    id: 'visibility',
    name: 'Visibility',
    fieldName: 'visibility',
    type: 2,
    unit: null,
  },
  wspd: {
    id: 'wspd',
    name: 'Wind Speed',
    fieldName: 'windSeed',
    type: 2,
    unit: 'mph',
  },
  windspeed: {
    id: 'windspeed',
    name: 'Wind Speed',
    fieldName: 'windSeed',
    type: 2,
    unit: 'mph',
  },

  datetimeStr: {
    id: 'datetimeStr',
    name: 'Date time',
    fieldName: 'datetime',
    type: 3,
    unit: null,
  },
  datetime: {
    id: 'datetime',
    name: 'Date time',
    fieldName: 'datetime',
    type: 3,
    unit: null,
  },
  datetimeEpoch: {
    id: 'datetimeEpoch',
    name: 'Date time in Unix',
    fieldName: 'datetimeEpoch',
    type: 3,
    unit: null,
  },
  cloudcover: {
    id: 'cloudcover',
    name: 'Cloud Cover',
    fieldName: 'cloudcover',
    type: 2,
    unit: '%',
  },
  mint: {
    id: 'mint',
    name: 'Minimum Temperature',
    fieldName: 'minTemperature',
    type: 2,
    unit: 'degC',
  },
  precip: {
    id: 'precip',
    name: 'Precipitation',
    fieldName: 'precipitation',
    type: 2,
    unit: 'mm',
  },
  sealevelpressure: {
    id: 'sealevelpressure',
    name: 'Sea Level Pressure',
    fieldName: 'seaLevelPressure',
    type: 2,
    unit: 'mb',
  },
  pressure: {
    id: 'pressure',
    name: 'Sea Level Pressure',
    fieldName: 'seaLevelPressure',
    type: 2,
    unit: 'mb',
  },
  snow: {
    id: 'snow',
    name: 'Snow',
    fieldName: 'snow',
    type: 2,
    unit: 'cm',
  },
  dew: {
    id: 'dew',
    name: 'Dew Point',
    fieldName: 'dewPoint',
    type: 2,
    unit: 'degC',
  },
  humidity: {
    id: 'humidity',
    name: 'Relative Humidity',
    fieldName: 'relativeHumidity',
    type: 2,
    unit: '%',
  },
  wgust: {
    id: 'wgust',
    name: 'Wind Gust',
    fieldName: 'windGust',
    type: 2,
    unit: 'mph',
  },
  windgust: {
    id: 'windgust',
    name: 'Wind Gust',
    fieldName: 'windGust',
    type: 2,
    unit: 'mph',
  },

  wdir: {
    id: 'wdir',
    name: 'Wind Direction',
    fieldName: 'windDirection',
    type: 2,
    unit: null,
  },
  winddir: {
    id: 'winddir',
    name: 'Wind Direction',
    fieldName: 'windDirection',
    type: 2,
    unit: null,
  },
  sunrise: {
    id: 'sunrise',
    name: 'Sunrise',
    fieldName: 'sunrise',
    type: 1,
    unit: null,
  },
  sunset: {
    id: 'sunset',
    name: 'Sunset',
    fieldName: 'sunset',
    type: 1,
    unit: null,
  },
  moonphase: {
    id: 'moonphase',
    name: 'Moon Phase',
    fieldName: 'moonphase',
    type: 2,
    unit: null,
  },
  weathertype: {
    id: 'weathertype',
    name: 'Weather Type',
    type: 1,
    unit: null,
  },
  conditions: {
    id: 'conditions',
    name: 'Conditions',
    type: 1,
    unit: null,
  },
};

// data returned by weather history api
export const mockWeatherHistoryData = {
  columns: {
    wdir: {
      id: 'wdir',
      name: 'Wind Direction',
      type: 2,
      unit: null,
    },
    latitude: {
      id: 'latitude',
      name: 'Latitude',
      type: 2,
      unit: null,
    },
    cloudcover: {
      id: 'cloudcover',
      name: 'Cloud Cover',
      type: 2,
      unit: '%',
    },
    mint: {
      id: 'mint',
      name: 'Minimum Temperature',
      type: 2,
      unit: 'degC',
    },
    datetime: {
      id: 'datetime',
      name: 'Date time',
      type: 3,
      unit: null,
    },
    precip: {
      id: 'precip',
      name: 'Precipitation',
      type: 2,
      unit: 'mm',
    },
    solarradiation: {
      id: 'solarradiation',
      name: 'Solar Radiation',
      type: 2,
      unit: 'W/m^2',
    },
    dew: {
      id: 'dew',
      name: 'Dew Point',
      type: 2,
      unit: 'degC',
    },
    humidity: {
      id: 'humidity',
      name: 'Relative Humidity',
      type: 2,
      unit: '%',
    },
    precipcover: {
      id: 'precipcover',
      name: 'Precipitation Cover',
      type: 2,
      unit: '%',
    },
    longitude: {
      id: 'longitude',
      name: 'Longitude',
      type: 2,
      unit: null,
    },
    info: {
      id: 'info',
      name: 'Info',
      type: 1,
      unit: null,
    },
    temp: {
      id: 'temp',
      name: 'Temperature',
      type: 2,
      unit: 'degC',
    },
    address: {
      id: 'address',
      name: 'Address',
      type: 1,
      unit: null,
    },
    maxt: {
      id: 'maxt',
      name: 'Maximum Temperature',
      type: 2,
      unit: 'degC',
    },
    visibility: {
      id: 'visibility',
      name: 'Visibility',
      type: 2,
      unit: null,
    },
    wspd: {
      id: 'wspd',
      name: 'Wind Speed',
      type: 2,
      unit: 'mph',
    },
    solarenergy: {
      id: 'solarenergy',
      name: 'Solar Energy',
      type: 2,
      unit: 'J/m^2',
    },
    resolvedAddress: {
      id: 'resolvedAddress',
      name: 'Resolved Address',
      type: 1,
      unit: null,
    },
    heatindex: {
      id: 'heatindex',
      name: 'Heat Index',
      type: 2,
      unit: 'degC',
    },
    weathertype: {
      id: 'weathertype',
      name: 'Weather Type',
      type: 1,
      unit: null,
    },
    snowdepth: {
      id: 'snowdepth',
      name: 'Snow Depth',
      type: 2,
      unit: 'cm',
    },
    sealevelpressure: {
      id: 'sealevelpressure',
      name: 'Sea Level Pressure',
      type: 2,
      unit: 'mb',
    },
    snow: {
      id: 'snow',
      name: 'Snow',
      type: 2,
      unit: 'cm',
    },
    name: {
      id: 'name',
      name: 'Name',
      type: 1,
      unit: null,
    },
    wgust: {
      id: 'wgust',
      name: 'Wind Gust',
      type: 2,
      unit: 'mph',
    },
    conditions: {
      id: 'conditions',
      name: 'Conditions',
      type: 1,
      unit: null,
    },
    windchill: {
      id: 'windchill',
      name: 'Wind Chill',
      type: 2,
      unit: 'degC',
    },
  },
  remainingCost: 0,
  queryCost: 8,
  messages: null,
  locations: {
    'Tirana,AL': {
      stationContributions: null,
      values: [
        {
          wdir: 202.83,
          temp: 27.1,
          maxt: 35.6,
          visibility: 7.2,
          wspd: 9,
          datetimeStr: '2019-06-13T00:00:00+02:00',
          solarenergy: null,
          heatindex: 35.9,
          cloudcover: 10.6,
          mint: 19.9,
          datetime: 1560384000000,
          precip: 0,
          solarradiation: null,
          weathertype: 'Mist',
          snowdepth: 0,
          sealevelpressure: 1011,
          snow: 0,
          dew: 18.6,
          humidity: 63.05,
          precipcover: 0,
          wgust: null,
          conditions: 'Clear',
          windchill: null,
          info: null,
        },
        {
          wdir: 253.63,
          temp: 25.3,
          maxt: 32.7,
          visibility: 7.2,
          wspd: 10.2,
          datetimeStr: '2019-06-14T00:00:00+02:00',
          solarenergy: null,
          heatindex: 33.6,
          cloudcover: 17.3,
          mint: 17,
          datetime: 1560470400000,
          precip: 0,
          solarradiation: null,
          weathertype: '',
          snowdepth: 0,
          sealevelpressure: 1012,
          snow: 0,
          dew: 17.3,
          humidity: 63.58,
          precipcover: 0,
          wgust: null,
          conditions: 'Clear',
          windchill: null,
          info: null,
        },
        {
          wdir: 241.33,
          temp: 27.6,
          maxt: 35.6,
          visibility: 6.2,
          wspd: 8.5,
          datetimeStr: '2019-06-15T00:00:00+02:00',
          solarenergy: null,
          heatindex: 41,
          cloudcover: 33.4,
          mint: 20.4,
          datetime: 1560556800000,
          precip: 0,
          solarradiation: null,
          weathertype: '',
          snowdepth: 0,
          sealevelpressure: 1008.8,
          snow: 0,
          dew: 20.6,
          humidity: 68.13,
          precipcover: 0,
          wgust: null,
          conditions: 'Partially cloudy',
          windchill: null,
          info: null,
        },
        {
          wdir: 204.13,
          temp: 27.9,
          maxt: 32.6,
          visibility: 6.6,
          wspd: 9.2,
          datetimeStr: '2019-06-16T00:00:00+02:00',
          solarenergy: null,
          heatindex: 36.4,
          cloudcover: 45.6,
          mint: 22.5,
          datetime: 1560643200000,
          precip: 0,
          solarradiation: null,
          weathertype: 'Lightning Without Thunder, Thunderstorm, Thunderstorm Without Precipitation, Light Rain',
          snowdepth: 0,
          sealevelpressure: 1007.4,
          snow: 0,
          dew: 20.7,
          humidity: 66.74,
          precipcover: 0,
          wgust: 35.8,
          conditions: 'Partially cloudy',
          windchill: null,
          info: null,
        },
        {
          wdir: 239.22,
          temp: 26.6,
          maxt: 32.2,
          visibility: 6.6,
          wspd: 6.9,
          datetimeStr: '2019-06-17T00:00:00+02:00',
          solarenergy: null,
          heatindex: 36.4,
          cloudcover: 50.5,
          mint: 21.3,
          datetime: 1560729600000,
          precip: 0.01,
          solarradiation: null,
          weathertype: 'Lightning Without Thunder, Rain, Thunderstorm Without Precipitation, Sky Coverage Decreasing',
          snowdepth: 0,
          sealevelpressure: 1008.2,
          snow: 0,
          dew: 21.4,
          humidity: 74.65,
          precipcover: 4.17,
          wgust: null,
          conditions: 'Rain, Partially cloudy',
          windchill: null,
          info: null,
        },
        {
          wdir: 231.29,
          temp: 26.2,
          maxt: 32.9,
          visibility: 7,
          wspd: 8.8,
          datetimeStr: '2019-06-18T00:00:00+02:00',
          solarenergy: null,
          heatindex: 35.8,
          cloudcover: 45.5,
          mint: 20.7,
          datetime: 1560816000000,
          precip: 0,
          solarradiation: null,
          weathertype: 'Lightning Without Thunder, Thunderstorm, Sky Coverage Decreasing',
          snowdepth: 0,
          sealevelpressure: 1009.1,
          snow: 0,
          dew: 20,
          humidity: 70.2,
          precipcover: 4.17,
          wgust: null,
          conditions: 'Partially cloudy',
          windchill: null,
          info: null,
        },
        {
          wdir: 236.13,
          temp: 26.1,
          maxt: 32.4,
          visibility: 6.3,
          wspd: 11.1,
          datetimeStr: '2019-06-19T00:00:00+02:00',
          solarenergy: null,
          heatindex: 35.2,
          cloudcover: 33,
          mint: 20.3,
          datetime: 1560902400000,
          precip: 0,
          solarradiation: null,
          weathertype: 'Lightning Without Thunder',
          snowdepth: 0,
          sealevelpressure: 1009,
          snow: 0,
          dew: 20.3,
          humidity: 72.33,
          precipcover: 0,
          wgust: null,
          conditions: 'Partially cloudy',
          windchill: null,
          info: null,
        },
        {
          wdir: 233.5,
          temp: 25.4,
          maxt: 31.5,
          visibility: 7.1,
          wspd: 9.1,
          datetimeStr: '2019-06-20T00:00:00+02:00',
          solarenergy: null,
          heatindex: 34.3,
          cloudcover: 22.3,
          mint: 19,
          datetime: 1560988800000,
          precip: 0,
          solarradiation: null,
          weathertype: 'Lightning Without Thunder, Sky Coverage Decreasing',
          snowdepth: 0,
          sealevelpressure: 1008.8,
          snow: 0,
          dew: 20,
          humidity: 74.07,
          precipcover: 0,
          wgust: null,
          conditions: 'Clear',
          windchill: null,
          info: null,
        },
      ],
      id: 'Tirana,AL',
      address: 'Tiranë, Shqipëria',
      name: 'Tiranë, Shqipëria',
      index: 0,
      latitude: 41.3223,
      longitude: 19.8252,
      distance: 0,
      time: 0,
      tz: 'Europe/Tirane',
      currentConditions: null,
      alerts: null,
    },
  },
};

export const mockHourlyWeatherData = {
  queryCost: 1,
  latitude: 42.5051,
  longitude: 1.52604,
  resolvedAddress: 'Andorra la Vella, Andorra',
  address: 'Andorra la Vella,AD',
  timezone: 'Z',
  tzoffset: 0,
  description: 'Similar temperatures continuing with no rain expected.',
  days: [
    {
      datetime: '2022-12-20',
      datetimeEpoch: 1671494400,
      tempmax: 8.3,
      tempmin: 2.4,
      temp: 5.3,
      feelslikemax: 6.7,
      feelslikemin: 0.3,
      feelslike: 4.3,
      dew: -5.2,
      humidity: 49.5,
      precip: 0.1,
      precipprob: 66.7,
      precipcover: 4.17,
      preciptype: ['rain'],
      snow: 0,
      snowdepth: 4.9,
      windgust: 31.7,
      windspeed: 9.7,
      winddir: 131.8,
      pressure: 1022.9,
      cloudcover: 64,
      visibility: 21,
      solarradiation: 88.3,
      solarenergy: 7.6,
      uvindex: 4,
      severerisk: 10,
      sunrise: '07:19:46',
      sunriseEpoch: 1671520786,
      sunset: '16:23:14',
      sunsetEpoch: 1671553394,
      moonphase: 0.95,
      conditions: 'Rain, Partially cloudy',
      description: 'Partly cloudy throughout the day with late afternoon rain.',
      icon: 'rain',
      stations: ['remote'],
      source: 'comb',
      hours: [
        {
          datetime: '00:00:00',
          datetimeEpoch: 1671494400,
          temp: 4.9,
          feelslike: 4.9,
          humidity: 30.59,
          dew: -11,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 5.4,
          preciptype: null,
          windgust: 9.4,
          windspeed: 3.6,
          winddir: 115,
          pressure: 1026,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '01:00:00',
          datetimeEpoch: 1671498000,
          temp: 5,
          feelslike: 5,
          humidity: 24.65,
          dew: -13.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 5.4,
          preciptype: null,
          windgust: 9.7,
          windspeed: 3.6,
          winddir: 134,
          pressure: 1025,
          visibility: 24.1,
          cloudcover: 98.6,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '02:00:00',
          datetimeEpoch: 1671501600,
          temp: 4.9,
          feelslike: 4.9,
          humidity: 23.63,
          dew: -14.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 5.4,
          preciptype: null,
          windgust: 9.7,
          windspeed: 2.5,
          winddir: 138.5,
          pressure: 1025,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '03:00:00',
          datetimeEpoch: 1671505200,
          temp: 4.6,
          feelslike: 4.6,
          humidity: 22.78,
          dew: -14.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 5.4,
          preciptype: null,
          windgust: 8.3,
          windspeed: 2.5,
          winddir: 111.4,
          pressure: 1025,
          visibility: 24.1,
          cloudcover: 72.2,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '04:00:00',
          datetimeEpoch: 1671508800,
          temp: 4.6,
          feelslike: 4.6,
          humidity: 24.13,
          dew: -14.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 5.4,
          preciptype: null,
          windgust: 8.3,
          windspeed: 3.2,
          winddir: 83.6,
          pressure: 1024,
          visibility: 24.1,
          cloudcover: 99.3,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '05:00:00',
          datetimeEpoch: 1671512400,
          temp: 3.9,
          feelslike: 2.6,
          humidity: 30.05,
          dew: -12.1,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 5.4,
          preciptype: null,
          windgust: 10.4,
          windspeed: 5.4,
          winddir: 58.9,
          pressure: 1024,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '06:00:00',
          datetimeEpoch: 1671516000,
          temp: 2.8,
          feelslike: 1.1,
          humidity: 37.49,
          dew: -10.3,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 5.4,
          preciptype: null,
          windgust: 14.8,
          windspeed: 6.1,
          winddir: 49.9,
          pressure: 1024,
          visibility: 24.1,
          cloudcover: 99,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '07:00:00',
          datetimeEpoch: 1671519600,
          temp: 2.4,
          feelslike: 0.3,
          humidity: 44.42,
          dew: -8.5,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 5.4,
          preciptype: null,
          windgust: 18,
          windspeed: 7.2,
          winddir: 58.1,
          pressure: 1025,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '08:00:00',
          datetimeEpoch: 1671523200,
          temp: 3.1,
          feelslike: 1.3,
          humidity: 46.75,
          dew: -7.2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 5.4,
          preciptype: null,
          windgust: 18.7,
          windspeed: 6.5,
          winddir: 57,
          pressure: 1024,
          visibility: 24.1,
          cloudcover: 60.8,
          solarradiation: 12,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '09:00:00',
          datetimeEpoch: 1671526800,
          temp: 4.5,
          feelslike: 3.5,
          humidity: 50.88,
          dew: -4.8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 5.4,
          preciptype: null,
          windgust: 17.3,
          windspeed: 5,
          winddir: 66.5,
          pressure: 1024,
          visibility: 24.1,
          cloudcover: 63.3,
          solarradiation: 103,
          solarenergy: 0.4,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-day',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '10:00:00',
          datetimeEpoch: 1671530400,
          temp: 6.1,
          feelslike: 6.1,
          humidity: 57.78,
          dew: -1.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 5.3,
          preciptype: null,
          windgust: 15.5,
          windspeed: 4,
          winddir: 157.3,
          pressure: 1024,
          visibility: 24.1,
          cloudcover: 0,
          solarradiation: 240,
          solarenergy: 0.9,
          uvindex: 2,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-day',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '11:00:00',
          datetimeEpoch: 1671534000,
          temp: 7.1,
          feelslike: 6.1,
          humidity: 58.89,
          dew: -0.4,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 5.2,
          preciptype: null,
          windgust: 20.2,
          windspeed: 6.1,
          winddir: 160.3,
          pressure: 1023,
          visibility: 24.1,
          cloudcover: 0,
          solarradiation: 351,
          solarenergy: 1.3,
          uvindex: 4,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-day',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '12:00:00',
          datetimeEpoch: 1671537600,
          temp: 7.9,
          feelslike: 6.4,
          humidity: 50.33,
          dew: -1.8,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 5,
          preciptype: null,
          windgust: 27.4,
          windspeed: 8.3,
          winddir: 179,
          pressure: 1022,
          visibility: 24.1,
          cloudcover: 0,
          solarradiation: 397,
          solarenergy: 1.4,
          uvindex: 4,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-day',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '13:00:00',
          datetimeEpoch: 1671541200,
          temp: 8.3,
          feelslike: 6.7,
          humidity: 45.82,
          dew: -2.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 4.8,
          preciptype: null,
          windgust: 30.2,
          windspeed: 9.4,
          winddir: 170.1,
          pressure: 1021,
          visibility: 24.1,
          cloudcover: 0,
          solarradiation: 390,
          solarenergy: 1.4,
          uvindex: 4,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-day',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '14:00:00',
          datetimeEpoch: 1671544800,
          temp: 8.2,
          feelslike: 6.5,
          humidity: 46.48,
          dew: -2.6,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 4.6,
          preciptype: null,
          windgust: 31,
          windspeed: 9.7,
          winddir: 163.2,
          pressure: 1021,
          visibility: 24.1,
          cloudcover: 0,
          solarradiation: 318,
          solarenergy: 1.1,
          uvindex: 3,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-day',
          stations: ['remote'],
          source: 'obs',
        },
        {
          datetime: '15:00:00',
          datetimeEpoch: 1671548400,
          temp: 7.5,
          feelslike: 5.7,
          humidity: 50.96,
          dew: -2,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 4.5,
          preciptype: null,
          windgust: 31.7,
          windspeed: 9.7,
          winddir: 158.7,
          pressure: 1020,
          visibility: 24.1,
          cloudcover: 0,
          solarradiation: 220,
          solarenergy: 0.8,
          uvindex: 2,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '16:00:00',
          datetimeEpoch: 1671552000,
          temp: 6.4,
          feelslike: 4.4,
          humidity: 53.35,
          dew: -2.4,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 4.4,
          preciptype: null,
          windgust: 29.9,
          windspeed: 9.4,
          winddir: 153.3,
          pressure: 1021,
          visibility: 24.1,
          cloudcover: 0.2,
          solarradiation: 84,
          solarenergy: 0.3,
          uvindex: 1,
          severerisk: 10,
          conditions: 'Clear',
          icon: 'clear-day',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '17:00:00',
          datetimeEpoch: 1671555600,
          temp: 5.5,
          feelslike: 3.7,
          humidity: 59.79,
          dew: -1.7,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 4.4,
          preciptype: null,
          windgust: 29.2,
          windspeed: 7.9,
          winddir: 150.6,
          pressure: 1021,
          visibility: 24.1,
          cloudcover: 61.6,
          solarradiation: 3,
          solarenergy: 0,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Partially cloudy',
          icon: 'partly-cloudy-night',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '18:00:00',
          datetimeEpoch: 1671559200,
          temp: 5.1,
          feelslike: 3.4,
          humidity: 65.19,
          dew: -0.9,
          precip: 0,
          precipprob: 0,
          snow: 0,
          snowdepth: 4.4,
          preciptype: null,
          windgust: 25.6,
          windspeed: 7.2,
          winddir: 155.1,
          pressure: 1022,
          visibility: 24.1,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Overcast',
          icon: 'cloudy',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '19:00:00',
          datetimeEpoch: 1671562800,
          temp: 5,
          feelslike: 3.5,
          humidity: 68.58,
          dew: -0.3,
          precip: 0,
          precipprob: 66.7,
          snow: 0,
          snowdepth: 4.4,
          preciptype: ['rain'],
          windgust: 23,
          windspeed: 6.5,
          winddir: 122.1,
          pressure: 1022,
          visibility: 24.1,
          cloudcover: 94,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '20:00:00',
          datetimeEpoch: 1671566400,
          temp: 4.8,
          feelslike: 3.5,
          humidity: 73.16,
          dew: 0.4,
          precip: 0,
          precipprob: 66.7,
          snow: 0,
          snowdepth: 4.4,
          preciptype: ['rain'],
          windgust: 19.8,
          windspeed: 5.8,
          winddir: 107.2,
          pressure: 1022,
          visibility: 18.7,
          cloudcover: 99.3,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '21:00:00',
          datetimeEpoch: 1671570000,
          temp: 4.8,
          feelslike: 4.8,
          humidity: 73.69,
          dew: 0.5,
          precip: 0,
          precipprob: 66.7,
          snow: 0,
          snowdepth: 4.4,
          preciptype: ['rain'],
          windgust: 17.6,
          windspeed: 4.7,
          winddir: 139.8,
          pressure: 1021,
          visibility: 3.6,
          cloudcover: 88.6,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Partially cloudy',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '22:00:00',
          datetimeEpoch: 1671573600,
          temp: 4.5,
          feelslike: 4.5,
          humidity: 73.64,
          dew: 0.2,
          precip: 0,
          precipprob: 66.7,
          snow: 0,
          snowdepth: 4.4,
          preciptype: ['rain'],
          windgust: 14.8,
          windspeed: 3.6,
          winddir: 199.2,
          pressure: 1022,
          visibility: 0.2,
          cloudcover: 100,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
        {
          datetime: '23:00:00',
          datetimeEpoch: 1671577200,
          temp: 4.4,
          feelslike: 4.4,
          humidity: 74.15,
          dew: 0.2,
          precip: 0.1,
          precipprob: 66.7,
          snow: 0,
          snowdepth: 4.4,
          preciptype: ['rain'],
          windgust: 10.1,
          windspeed: 2.5,
          winddir: 52,
          pressure: 1021,
          visibility: 0.1,
          cloudcover: 99.8,
          solarradiation: 0,
          solarenergy: null,
          uvindex: 0,
          severerisk: 10,
          conditions: 'Rain, Overcast',
          icon: 'rain',
          stations: null,
          source: 'fcst',
        },
      ],
    },
  ],
  alerts: [],
  stations: {
    E4149: {
      distance: 44368,
      latitude: 42.316,
      longitude: 1.051,
      useCount: 0,
      id: 'E4149',
      name: 'EW4149 Peramea ES',
      quality: 0,
      contribution: 0,
    },
  },
  currentConditions: {
    datetime: '14:45:41',
    datetimeEpoch: 1671547541,
    temp: 8.4,
    feelslike: 8.4,
    humidity: 70.8,
    dew: 3.4,
    precip: 0,
    precipprob: 0,
    snow: 0,
    snowdepth: 0,
    preciptype: null,
    windgust: null,
    windspeed: 9.7,
    winddir: 158.7,
    pressure: 1020,
    visibility: null,
    cloudcover: 0,
    solarradiation: 220,
    solarenergy: 0.8,
    uvindex: 2,
    conditions: 'Clear',
    icon: 'clear-day',
    stations: ['E4149'],
    source: 'obs',
    sunrise: '07:19:46',
    sunriseEpoch: 1671520786,
    sunset: '16:23:14',
    sunsetEpoch: 1671553394,
    moonphase: 0.95,
  },
};
